sh
bryanhonof/pxl-infra pull request #74
Opened 2024-07-15 14:34 UTC by Anish-Pun

2024-07-15 14:34 UTC, Anish-Pun commented
ssh

2024-07-15 22:12 UTC, bryanhonof commented
Kan je die CNAME file a.u.b. verwijderen? Die hoort daar niet te zijn.

2024-07-16 12:39 UTC, bryanhonof commented
Je syntax klopt niet helemaal precies. Je mis de sluitende haakjes op 2 niveaus.

2024-07-16 12:40 UTC, bryanhonof requested changes

2024-07-16 12:40 UTC, bryanhonof commented on servers.tf
> +        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIrvcSz2EnQieZyeUOm7aiQN+WCng1uH8fp2Nt/BrAuo Anish.Pun@student.pxl.be",
```suggestion
    Anish = {
      ssh_keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIrvcSz2EnQieZyeUOm7aiQN+WCng1uH8fp2Nt/BrAuo Anish.Pun@student.pxl.be",
      ]
    }
```

2024-07-16 14:21 UTC, closed without merging